# Generated by Django 2.1.4 on 2019-01-17 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractDetails',
            fields=[
                ('ethereum_address', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('license_name', models.CharField(max_length=50)),
                ('validity_date', models.DateField()),
                ('hardware_id', models.CharField(max_length=200)),
                ('license_type', models.CharField(max_length=50)),
                ('contract_bytecode', models.TextField()),
                ('contract_abi', models.TextField()),
                ('tx_hash', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('ethereum_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admincontracts.ContractDetails')),
            ],
        ),
    ]
