# Generated by Django 2.1.4 on 2019-01-17 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admincontracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='user_details',
        ),
    ]
