# Generated by Django 2.1.4 on 2019-01-17 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admincontracts', '0002_auto_20190118_0328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_details',
            new_name='User',
        ),
    ]
