# Generated by Django 2.1.4 on 2019-01-17 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admincontracts', '0003_auto_20190118_0336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='userdetail',
        ),
    ]
