# Generated by Django 2.1.4 on 2019-01-17 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admincontracts', '0004_auto_20190118_0339'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userdetail',
            new_name='Users',
        ),
    ]
