# Generated by Django 2.1.4 on 2019-01-17 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admincontracts', '0005_auto_20190118_0356'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='userdetail',
        ),
    ]
